// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("deepdreamAnimation")>]
[<assembly: AssemblyProductAttribute("caffe.clr.demo")>]
[<assembly: AssemblyDescriptionAttribute("A demo and tutorial of how to use caffe.clr")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "deepdreamAnimation"
    let [<Literal>] AssemblyProduct = "caffe.clr.demo"
    let [<Literal>] AssemblyDescription = "A demo and tutorial of how to use caffe.clr"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
