open System.IO
open System.Drawing

let drawTextAndBox (g: Graphics) text fontSize left top =
    let font = new Font("Calibri", fontSize)
    let size = g.MeasureString(text, font)
    g.FillRectangle(new SolidBrush(Color.FromArgb(128, 255, 255, 255)), left - 12, top - 12, int size.Width + 24, int size.Height + 18)
    g.DrawString(text, font, Brushes.Black, float32 left, float32 top)

let test() =
    let img = Image.FromFile(Path.Combine(__SOURCE_DIRECTORY__, "maxcat_testtext.jpg"))
    let g = Graphics.FromImage(img)
    //drawTextAndBox g "This is Deep Dream" 22.f 24 24
    //drawTextAndBox g "images generated by ..." 18.f 24 24
    drawTextAndBox g "neural networks." 18.f 24 24
    drawTextAndBox g "Each sequence is ..." 18.f 24 24
    drawTextAndBox g "generated by ..." 18.f 24 24
    drawTextAndBox g "a different layer." 18.f 24 24
    drawTextAndBox g "Come see how ..." 18.f 24 24
    drawTextAndBox g "at F# exchange." 18.f 24 24
    drawTextAndBox g "more test" 12.f 24 (img.Height - 150)
    img.Save(Path.Combine(__SOURCE_DIRECTORY__, "maxcat_testtext_out.jpg"))

test() 
